const REQUEST_DATA_UNDEFINED = 1;
const EMPTY_REF_CODE_EMPTY = 2;
const FULL_REF_CODE_EMPTY = 3;
const FILES_EMPTY = 4;
const XIDMETLER_EMPTY = 5;
export default {
    REQUEST_DATA_UNDEFINED,
    EMPTY_REF_CODE_EMPTY,
    FULL_REF_CODE_EMPTY,
    FILES_EMPTY,
    XIDMETLER_EMPTY
};
